src/components/Modal/Nickname/Nickname.tsx
src/components/Modal/ProfileId/ProfileId.tsx

> Issue #5 
- 닉네임과 id API 호출을 모달별로 완전히 분리
- 엔터 눌러도 입력되도록 수정
- 프로필 URL (id) 중복 메시지 제대로 렌더링되도록 수정

Fix: 회원가입 로직 에러 수정

---

src/api/users/deleteMe.ts
src/components/ProfilePage/Profile/Profile.tsx
src/constants/baseurl.tsx

Fix: 회원 탈퇴 시 로컬스토리지 초기화 문제 해결

---

src/components/Detail/Detail.tsx
src/components/Detail/Similar/Similar.tsx
src/components/Layout/Header/Header.tsx

관련 작품은 혹시 몰라서 주석 처리만 했는데, 이로 인해 발생하는 빈 공간이 다소 있습니다. (스크린샷 참조)
필요하다면 임시로 여백을 줄여놓겠습니다!

Refactor: 관련 작품 및 헤더 검색창 웹뷰 토글 로직 삭제

---

package-lock.json
package.json
src/components/Notifications/Noti/Noti.tsx
tsconfig.json

> close #19 
제가 졸면서 고쳐서.. 에러가 있다면 알려주세요 😳

Refactor: 알림 타입 통일에 따른 리팩토링 

---

src/components/Detail/Author/Author.tsx
src/components/Detail/Detail.tsx
src/components/FollowingPage/FollowingFeed/FollowingFeed.tsx
src/components/FollowingPage/RecommendCard/RecommendCard.tsx
src/components/Layout/FollowNewFeed/FollowNewFeed.tsx
src/components/Layout/ProfileCard/ProfileCard.tsx
src/components/Layout/RectangleCard/RectangleCard.tsx
src/components/Layout/SquareCard/SquareCard.tsx
src/components/PopularPage/PopularFeed/FeedCard/FeedCard.tsx
src/components/PopularPage/PopularTag/Tag/Tag.tsx
src/components/PopularPage/PopularUser/PopularUser.tsx
src/components/PopularPage/PopularUser/User/User.tsx
src/components/ProfilePage/Profile/Profile.tsx
src/components/SearchPage/Feed/SearchCard/SearchCard.tsx
src/hooks/usePreventRightClick.ts

> close #23
토스트 말고 다른 방법 제안해주셔도 됩니다..!

Feat: 우클릭 방지 훅 구현 및 이미지에 적용

---

src/pages/_app.tsx

→ **메타 태그 에러 해결**
기존에는 AppProps에서 SSR로 값이 없을 때를 고려해 로딩 상태를 추가했었는데..
Next.js의 pageProps는 페이지 렌더링 전에 이미 값이 주입되기 때문에, 따로 클라이언트에서 isInitializing 같은 상태로 로딩을 처리할 필요가 없었습니다..😂
넥스트 공부 열심히 하겠습니다..ㅎ
(공식문서 링크: https://nextjs.org/docs/pages/building-your-application/routing/custom-app )

Fix: isInitializing 상태 및 Loader 삭제

---

src/components/Layout/Header/Header.module.scss
src/components/Layout/Header/Header.tsx

=> 초기 렌더링에도 보이도록 수정
> 다음과 같은 두번째 버그를 수정했습니다.
- 스크롤 전
- 스크롤 후
어차피 헤더 변경될 예정이라 대충만 수정했습니다..!~

Fix: 헤더 스크롤 및 아이콘 버그 수정

---

package-lock.json
package.json
src/components/ProfilePage/Profile/Profile.module.scss
src/components/ProfilePage/Profile/Profile.tsx
src/components/ProfilePage/ProfilePage.module.scss

Fix: 커버 이미지 프로필 영역에서 완전히 분리

---

src/components/Board/BoardAll/BoardAll.tsx

게시글 상세페이지 하단 게시글 리팩터링

---

src/components/Layout/Sidebar/Sidebar.tsx
src/pages/index.tsx
src/styles/pages/home.module.scss

`2560*1440 해상도 수정 전후`
---
`Sidebar`
Sidebar는 자유게시판 갔다가 로고 누르면 자유게시판 메뉴 active가 유지되는 오류 해결했습니다.
그리고 게시글 화면에서는 자유게시판 메뉴가 active 되어 보이는 게 자연스러울 거 같아서 추가했습니다!

Refactor: main layout max-width 지정

---

src/components/Modal/AlbumEdit/AlbumEdit.module.scss
src/components/Modal/AlbumEdit/AlbumEdit.tsx
src/components/Modal/AlbumMove/AlbumMove.tsx
src/components/Modal/AlbumSelect/AlbumSelect.tsx
src/components/Upload/EditFeeds/EditFeeds.module.scss
src/components/Upload/EditFeeds/EditFeeds.tsx
src/components/Upload/Upload.module.scss
src/components/Upload/Upload.tsx

> Close #69 
- 앨범 편집 모달
- 업로드/그림편집 페이지
- 앨범 편집
- 앨범 선택 

refactor: #69 앨범 기능 추가 리팩토링

---

src/components/Layout/MainBoard/MainBoard.tsx
src/components/Layout/Title/Title.module.scss

> Close #55 
디자이너님이 기존 PC, 태블릿과 모바일 시안이 다른 부분을 전부 통일해주셨습니다!
따라서 타이틀만 변경했습니다..

rename: 메인페이지 자유게시판 타이틀 변경

---

src/components/Layout/Sidebar/Sidebar.tsx
src/constants/menu.tsx

> 현재 홈 경로(`/`)일때 `/${route}`를 통해 이동하면 `//`가 되어 다음 콘솔 에러가 발생하여 수정했습니다!

fix: 사이드바 home 라우팅 이중 슬래시 제거

---

src/components/DatePicker/DatePicker.module.scss

[Design] Datepicker 간격 조정

---

src/api/feeds/getFeedsFollowing.ts
src/components/Board/BoardWrite/BoardWrite.tsx
src/components/FollowingPage/FollowingPage.tsx
src/components/Layout/AuthLayout/AuthLayout.tsx
src/components/Upload/Upload.tsx
src/pages/_app.tsx
src/pages/board/write.tsx
src/pages/following.tsx
src/pages/mypage.tsx
src/pages/write.tsx
src/states/authStore.ts

- `authStore.ts` 수정
- `isAuthReady` 상태를 추가하여 앱의 초기 인증 확인 절차가 완료되었는지 여부를 추적합니다. 이를 통해 비동기적으로 `localStorage`를 확인하는 동안 발생할 수 있는 race condition를 방지합니다.
- `_app.tsx` 로직 개선
- 앱이 처음 로드될 때 `localStorage`에서 인증 토큰을 확인하고, `zustand` 스토어의 상태를 업데이트하는 로직을 중앙화했습니다.
- 인증 확인이 완료되면 `isAuthReady`를 `true`로 설정하여, 애플리케이션의 다른 모든 컴포넌트가 안정적으로 인증 상태를 참조할 수 있도록 합니다.
- `<AuthLayout />` 컴포넌트 신규 생성
- 로그인이 필요한 페이지를 감싸는 `AuthLayout` 컴포넌트를 새로 만들었습니다.
- 이 컴포넌트는 `isAuthReady`와 `isLoggedIn` 상태를 확인합니다.
- 인증 확인이 완료될 때까지 로딩 UI(Loader)를 보여줍니다.
- 인증 확인 후 로그인이 되어있지 않으면, 로그인 모달을 띄우고 홈페이지(/)로 리디렉션합니다.
- `following.tsx` 리팩토링
- 기존에 `following.tsx` 페이지 내에 있던 복잡한 인증 관련 `useEffect` 로직을 모두 제거했습니다.
이제 페이지 전체를 `<AuthLayout>`으로 감싸는 간결한 구조로 변경하여, 모든 인증 관련 책임을 `AuthLayout`에 위임합니다.
https://github.com/user-attachments/assets/9b33f73b-4060-4a3f-a5 …

[Fix] 인증 로직 리팩토링 및 AuthLayout 구현

---

src/components/Modal/Background/Background.tsx
src/components/Modal/Modal.tsx
src/components/ProfilePage/Profile/ProfileCover/ProfileCover.tsx
src/hooks/useCoverImage.ts

- #108
- **이미지 크롭 모달 안정성 향상**
- `react-image-crop` 사용 시, 크롭 영역을 조절하다 마우스가 모달 밖으로 나가면 모달이 닫히던 문제를 해결했습니다. (`onClick` -> `onMouseDown/Up` 로직 변경)
- 이미지를 불러온 후, 크롭 영역을 따로 지정하지 않고 바로 저장할 때 발생하던 오류를 수정했습니다. (`completedCrop` 초기값 설정)
- **화면 깜빡임 현상 제거**
-  커버 이미지 변경 및 삭제 시 `router.reload()`로 인해 발생하던 전체 페이지 새로고침을 제거했습니다.
-  대신 `react-query`의 `refetch`를 사용하여 데이터만 비동기적으로 갱신하도록 변경하여, 사용자가 부드러운 UI 업데이트를 경험할 수 있도록 개선했습니다.
- **데이터 동기화 문제 해결**
- 커버 이미지 변경 후, 프로필 페이지의 데이터가 실시간으로 갱신되지 않던 문제를 해결했습니다.
- 모달과 프로필 페이지 간에 데이터 갱신 함수(`refetch`)를 공유하여, 이미지 업로드 성공 시 프로필 데이터가 올바르게 다시 로드되도록 수정했습니다.
- **파일 재선택 버그 수정**
- 동일한 커버 이미지 파일을 연속으로 선택하면 `onChange` 이벤트가 발생하지 않던 버그를 수정했습니다.
- 파일 입력(`input`) 컴포넌트를 클릭할 때마다 값을 초기화하여, 항상 파일 선택 이벤트를 감지하도록 변경했습니다.
- 영상을 올릴려고 했으나, 용량이 커서 해당 브런치에 접근하셔서 확인해주시면 감사드리겠습니다 :)

[Fix] 프로필 커버 이미지 관리 기능 개선

---

src/api/feeds/putFeedsId.ts
src/components/Modal/FeedConfirm/index.tsx
src/components/Modal/Portal/index.tsx
src/components/Modal/Provider/index.tsx
src/components/Modal/Upload/Upload.module.scss
src/components/Modal/Upload/Upload.tsx
src/components/Modal/Upload/Upload.types.ts
src/components/Upload/EditFeeds/EditFeeds.tsx
src/components/Upload/FeedForm/FeedForm.tsx
src/components/Upload/FeedForm/FeedForm.types.ts
src/components/Upload/Upload.tsx
src/hooks/useModal.ts
src/pages/_app.tsx
src/states/modalStore.ts

- **게시물 중복 생성 수정**
- 게시물 업로드 시, 확인 모달의 버튼을 빠르게 중복 클릭하면 동일한 게시물이 여러 번 생성되는 문제를 수정했습니다. 
- 기존에는 모달 내 버튼을 disabled 처리하려면, 새로운 모달 타입을 추가하고 컴포넌트를 별도로 만들어야 하는 번거로움이 있었습니다.
- 이에 따라 중복 클릭을 방지할 수 있도록 새로운 모달 처리 로직을 도입했지만, 단순한 텍스트/버튼만 있는 모달도 있다 보니 현재 방식은 반복 작업이 필요합니다. → 로직을 좀 더 개선할 여지가 있어 추가 고민 중입니다.
- `router.push`로 인해 활성화 안되어있던 업로드 성공 모달도 활성화할 수 있었습니다.
- **피드 제출 후 불필요한 확인 모달 버그 수정**
- 피드 생성 또는 수정 후 페이지 이동 시, “저장되지 않은 변경사항이 있습니다”라는 확인 모달이 잘못 표시되던 문제를 수정했습니다.
- 원인은, API 요청이 성공한 뒤 `router.push()`로 페이지가 이동할 때도 `FeedForm`의 `hasUnsavedChanges` 상태가 `true`로 남아 있어 `routeChangeStart` 이벤트에서 변경사항이 있다고 모달이 활성화되었습니다.
- 그래서 오인하지 않도록 상태를 추가하여 이를 제어했습니다.
- 피드 업로드 파일 제거했다가 재등록 시 등록 안됐던 이슈를 수정했습니다.
https://github.com/user-attachments/assets/8b61c4a8-4dc9-4e5d-9d85-4bd551742115 …

[Fix] 게시물 - 업로드 중복 수정 및 피드 제출 후 불필요한 확인 모달 버그 수정

---

src/components/Layout/AuthLayout/AuthLayout.tsx
src/components/Layout/Header/Header.tsx
src/components/Modal/Login/Login.module.scss
src/components/Modal/Login/Login.tsx
src/components/Modal/Modal.tsx
src/hooks/useOnClickOutside.ts
src/states/modalStore.ts

- #101 
https://github.com/user-attachments/assets/3cae8e51-74a3-465b-a33f-7d312185441e

[Fix] 헤더 - 모달 중복 활성화 수정

---

src/components/Layout/Header/Header.module.scss
src/components/Layout/Layout.module.scss
src/components/Modal/Login/Login.module.scss
src/components/Modal/Provider/index.tsx
src/hooks/usePreventScroll.ts
src/styles/globals.scss

- #122 
- 로그인 모달의 스타일을 수정했습니다.
- 모달이 활성화 되었을 때, 스크롤 기능을 막았습니다.
- 아래로 스크롤 된 이후 모달이 활성화 되었을 때, 스크롤바가 사라지면서 화면이 **Layout shift**가 발생했습니다. 
- 스크롤바 크기에 맞게 `padding-right`을 추가하여 해당 문제를 해결했습니다.
- 헤더와 플로팅 버튼은 `position: fixed`로 고정되어 있기 때문에, 모달이 열릴 때 `body`에 `openModal` 클래스명을 추가하여 스크롤바 너비와 `right` 값을 합산해 위치가 밀리지 않도록 조정했습니다.
https://github.com/user-attachments/assets/a0e2d83a-d8eb-429c-84c4-10b2ebb1c154

[Fix] 로그인 모달 수정 및 모달 활성화 시 스크롤 막기

---

src/components/Modal/Follow/Follow.tsx

- 팔로우 목록 중 `description`이 없는 경우 `follow.id`로 잘못된 URL로 보내고 있어 이를 수정했습니다.
**AS-IS**
https://github.com/user-attachments/assets/4cd99c62-aeeb-402e-b039-73a6260c6aaf
**TO-BE**
https://github.com/user-attachments/assets/90b4cd5e-f86f-47a7-827a-6227b918285b

[Fix] 팔로우 목록 클릭 시 잘못된 URL 이동 수정

---

src/components/Layout/FooterSection/FooterSection.tsx
src/components/Layout/Header/Contact/Contact.tsx
src/components/Modal/Nickname/Nickname.tsx

GCP 콘솔에서 뜨는 경고문구를 없애기 위해 이용약관 및 개인정보처리방침 링크를 자체 도메인에 물리도록 수정했습니다.

fix: 이용약관 및 개인정보처리방침 링크 수정

---

src/components/Board/BoardWrite/PostForm/PostForm.tsx

- 에디터에 그리미티 주소를 링크를 등록할 경우, 기본 설정으로 인해 상대경로로 저장되는 문제가 있었습니다. 모바일 환경에서는 상대경로가 정상적으로 동작하지 않아 절대경로가 필요했습니다.
- 이를 해결하기 위해 TinyMCE 설정에서 아래 두 옵션을 false로 수정했습니다.
```
{
relative_urls: false,
remove_script_host: false,
}
```
- [TinyMCE 공식문서](https://www.tiny.cloud/docs/tinymce/latest/url-handling)
**AS-IS**
**TO-BE**
- 이미 상대경로로 저장한 것은 유저가 직접 수정을 하지 않는 이상은 절대경로로 변경되지 않습니다.

[Fix] 에디터 링크 사용 시 절대경로로 적용되게 수정

---

src/components/Modal/AlbumSelect/AlbumSelect.module.scss
src/components/ProfilePage/Profile/ProfileImage/ProfileImage.module.scss
src/components/ProfilePage/ProfilePage.module.scss
src/components/ProfilePage/ProfilePage.tsx
src/pages/[url].tsx

- 앨범선택: safearea 설정하는 구간을 변경했습니다. 
- 프로필: 모바일에서 아이콘 색상을 파란색에서 gray70으로 변경했습니다.
**AS-IS**
**TO-BE**
- 앨범선택은 시뮬레이터로 돌린거라 배포하고 실제 폰으로 테스트가 필요합니다.

[Fix] 앨범선택 - safearea 설정 구간 변경, 프로필 - 아이콘 색상 변경

---

src/components/Layout/Layout.tsx
src/components/Modal/Modal.module.scss
src/pages/_app.tsx
src/pages/_document.tsx
src/styles/globals.scss
src/styles/reset.css
src/utils/viewport.ts

- #145
- 모바일에서 주소창으로 인해 100vh가 제대로 설정되지 않아 `window.innerHeight`와 resize를 이용하여 현재 높이를 계산하여 보이도록 했습니다.
- 모바일에서 인풋 선택 시 확대되는 이슈가 있어 이를 수정했습니다.

[Fix] 모달 - 반응형 높이 설정
